using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace DataAccess.Migrations
{
    /// <inheritdoc />
    public partial class mig1 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ApplicationTypes",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CaseTypeID = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ApplicationTypes", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "CaseTypes",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaseTypes", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "Cities",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Cities", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "Defendants",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Defendants", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "DocumentTypes",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Type = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DocumentTypes", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "Districts",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CityID = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Districts", x => x.ID);
                    table.ForeignKey(
                        name: "FK_Districts_Cities_CityID",
                        column: x => x.CityID,
                        principalTable: "Cities",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CaseFiles",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CaseTypeID = table.Column<int>(type: "int", nullable: false),
                    ApplicationTypeID = table.Column<int>(type: "int", nullable: false),
                    CityID = table.Column<int>(type: "int", nullable: false),
                    DistrictID = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Surname = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IdentityNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PhoneNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DateOfBirth = table.Column<DateTime>(type: "datetime2", nullable: false),
                    EntitlementRate = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false),
                    DisabilityRate = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false),
                    AccidentDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    OpeningDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ClosingDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CaseStatus = table.Column<int>(type: "int", nullable: false),
                    CaseTypeID1 = table.Column<int>(type: "int", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaseFiles", x => x.ID);
                    table.ForeignKey(
                        name: "FK_CaseFiles_ApplicationTypes_ApplicationTypeID",
                        column: x => x.ApplicationTypeID,
                        principalTable: "ApplicationTypes",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaseFiles_CaseTypes_CaseTypeID",
                        column: x => x.CaseTypeID,
                        principalTable: "CaseTypes",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaseFiles_CaseTypes_CaseTypeID1",
                        column: x => x.CaseTypeID1,
                        principalTable: "CaseTypes",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaseFiles_Cities_CityID",
                        column: x => x.CityID,
                        principalTable: "Cities",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaseFiles_Districts_DistrictID",
                        column: x => x.DistrictID,
                        principalTable: "Districts",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CityID = table.Column<int>(type: "int", nullable: true),
                    DistrictID = table.Column<int>(type: "int", nullable: true),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Surname = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Mail = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UserName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Password = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.ID);
                    table.ForeignKey(
                        name: "FK_Users_Cities_CityID",
                        column: x => x.CityID,
                        principalTable: "Cities",
                        principalColumn: "ID");
                    table.ForeignKey(
                        name: "FK_Users_Districts_DistrictID",
                        column: x => x.DistrictID,
                        principalTable: "Districts",
                        principalColumn: "ID");
                });

            migrationBuilder.CreateTable(
                name: "CaseFileDefendant",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    caseFileID = table.Column<int>(type: "int", nullable: false),
                    defendantID = table.Column<int>(type: "int", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaseFileDefendant", x => x.ID);
                    table.ForeignKey(
                        name: "FK_CaseFileDefendant_CaseFiles_caseFileID",
                        column: x => x.caseFileID,
                        principalTable: "CaseFiles",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaseFileDefendant_Defendants_defendantID",
                        column: x => x.defendantID,
                        principalTable: "Defendants",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CaseFileDocument",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CaseFileID = table.Column<int>(type: "int", nullable: false),
                    DocumentTypeID = table.Column<int>(type: "int", nullable: false),
                    DocumentUrl = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    CaseFileID1 = table.Column<int>(type: "int", nullable: true),
                    DocumentTypeID1 = table.Column<int>(type: "int", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaseFileDocument", x => x.ID);
                    table.ForeignKey(
                        name: "FK_CaseFileDocument_CaseFiles_CaseFileID",
                        column: x => x.CaseFileID,
                        principalTable: "CaseFiles",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaseFileDocument_CaseFiles_CaseFileID1",
                        column: x => x.CaseFileID1,
                        principalTable: "CaseFiles",
                        principalColumn: "ID");
                    table.ForeignKey(
                        name: "FK_CaseFileDocument_DocumentTypes_DocumentTypeID",
                        column: x => x.DocumentTypeID,
                        principalTable: "DocumentTypes",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaseFileDocument_DocumentTypes_DocumentTypeID1",
                        column: x => x.DocumentTypeID1,
                        principalTable: "DocumentTypes",
                        principalColumn: "ID");
                });

            migrationBuilder.CreateTable(
                name: "CaseFileShares",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CaseFileID = table.Column<int>(type: "int", nullable: false),
                    UserID = table.Column<int>(type: "int", nullable: false),
                    ShareRate = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    FilePermission = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaseFileShares", x => x.ID);
                    table.ForeignKey(
                        name: "FK_CaseFileShares_CaseFiles_CaseFileID",
                        column: x => x.CaseFileID,
                        principalTable: "CaseFiles",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaseFileShares_Users_UserID",
                        column: x => x.UserID,
                        principalTable: "Users",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "HesapHareketler",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    DebtorID = table.Column<int>(type: "int", nullable: false),
                    CreditID = table.Column<int>(type: "int", nullable: false),
                    CaseFileID = table.Column<int>(type: "int", nullable: true),
                    Amount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    TransactionStatus = table.Column<byte>(type: "tinyint", nullable: false),
                    Type = table.Column<byte>(type: "tinyint", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    PaymentDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PaymentReceivedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    FinalPaymentDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PaymentStatus = table.Column<bool>(type: "bit", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: false, defaultValue: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HesapHareketler", x => x.ID);
                    table.ForeignKey(
                        name: "FK_HesapHareketler_CaseFiles_CaseFileID",
                        column: x => x.CaseFileID,
                        principalTable: "CaseFiles",
                        principalColumn: "ID");
                    table.ForeignKey(
                        name: "FK_HesapHareketler_Users_CreditID",
                        column: x => x.CreditID,
                        principalTable: "Users",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_HesapHareketler_Users_DebtorID",
                        column: x => x.DebtorID,
                        principalTable: "Users",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "ApplicationTypes",
                columns: new[] { "ID", "CaseTypeID", "CreatedDate", "DeletedDate", "Name", "Status", "UpdatedDate" },
                values: new object[,]
                {
                    { 1, 1, new DateTime(2025, 4, 14, 10, 39, 2, 727, DateTimeKind.Local).AddTicks(9350), null, "Araç Hasarı", false, null },
                    { 2, 1, new DateTime(2025, 4, 14, 10, 39, 2, 727, DateTimeKind.Local).AddTicks(9366), null, "Manevi", false, null },
                    { 3, 1, new DateTime(2025, 4, 14, 10, 39, 2, 727, DateTimeKind.Local).AddTicks(9366), null, "İdari Dava", false, null },
                    { 4, 4, new DateTime(2025, 4, 14, 10, 39, 2, 727, DateTimeKind.Local).AddTicks(9367), null, "Kamulaştırma", false, null }
                });

            migrationBuilder.InsertData(
                table: "CaseTypes",
                columns: new[] { "ID", "CreatedDate", "DeletedDate", "Name", "Status", "UpdatedDate" },
                values: new object[,]
                {
                    { 1, new DateTime(2025, 4, 14, 10, 39, 2, 727, DateTimeKind.Local).AddTicks(9705), null, "Trafik Kazası", false, null },
                    { 2, new DateTime(2025, 4, 14, 10, 39, 2, 727, DateTimeKind.Local).AddTicks(9708), null, "Arabuluculuk", false, null },
                    { 3, new DateTime(2025, 4, 14, 10, 39, 2, 727, DateTimeKind.Local).AddTicks(9709), null, "İdari Dava", false, null },
                    { 4, new DateTime(2025, 4, 14, 10, 39, 2, 727, DateTimeKind.Local).AddTicks(9710), null, "Kamulaştırma", false, null }
                });

            migrationBuilder.InsertData(
                table: "Cities",
                columns: new[] { "ID", "Name" },
                values: new object[,]
                {
                    { 1, "Adana" },
                    { 2, "Adıyaman" },
                    { 3, "Afyonkarahisar" },
                    { 4, "Ağrı" },
                    { 5, "Amasya" },
                    { 6, "Ankara" },
                    { 7, "Antalya" },
                    { 8, "Artvin" },
                    { 9, "Aydın" },
                    { 10, "Balıkesir" },
                    { 11, "Bilecik" },
                    { 12, "Bingöl" },
                    { 13, "Bitlis" },
                    { 14, "Bolu" },
                    { 15, "Burdur" },
                    { 16, "Bursa" },
                    { 17, "Çanakkale" },
                    { 18, "Çankırı" },
                    { 19, "Çorum" },
                    { 20, "Denizli" },
                    { 21, "Diyarbakır" },
                    { 22, "Edirne" },
                    { 23, "Elazığ" },
                    { 24, "Erzincan" },
                    { 25, "Erzurum" },
                    { 26, "Eskişehir" },
                    { 27, "Gaziantep" },
                    { 28, "Giresun" },
                    { 29, "Gümüşhane" },
                    { 30, "Hakkari" },
                    { 31, "Hatay" },
                    { 32, "Isparta" },
                    { 33, "Mersin" },
                    { 34, "İstanbul" },
                    { 35, "İzmir" },
                    { 36, "Kars" },
                    { 37, "Kastamonu" },
                    { 38, "Kayseri" },
                    { 39, "Kırklareli" },
                    { 40, "Kırşehir" },
                    { 41, "Kocaeli" },
                    { 42, "Konya" },
                    { 43, "Kütahya" },
                    { 44, "Malatya" },
                    { 45, "Manisa" },
                    { 46, "Kahramanmaraş" },
                    { 47, "Mardin" },
                    { 48, "Muğla" },
                    { 49, "Muş" },
                    { 50, "Nevşehir" },
                    { 51, "Niğde" },
                    { 52, "Ordu" },
                    { 53, "Rize" },
                    { 54, "Sakarya" },
                    { 55, "Samsun" },
                    { 56, "Siirt" },
                    { 57, "Sinop" },
                    { 58, "Sivas" },
                    { 59, "Tekirdağ" },
                    { 60, "Tokat" },
                    { 61, "Trabzon" },
                    { 62, "Tunceli" },
                    { 63, "Şanlıurfa" },
                    { 64, "Uşak" },
                    { 65, "Van" },
                    { 66, "Yozgat" },
                    { 67, "Zonguldak" },
                    { 68, "Aksaray" },
                    { 69, "Bayburt" },
                    { 70, "Karaman" },
                    { 71, "Kırıkkale" },
                    { 72, "Batman" },
                    { 73, "Şırnak" },
                    { 74, "Bartın" },
                    { 75, "Ardahan" },
                    { 76, "Iğdır" },
                    { 77, "Yalova" },
                    { 78, "Karabük" },
                    { 79, "Kilis" },
                    { 80, "Osmaniye" },
                    { 81, "Düzce" }
                });

            migrationBuilder.InsertData(
                table: "DocumentTypes",
                columns: new[] { "ID", "CreatedDate", "DeletedDate", "Name", "Status", "Type", "UpdatedDate" },
                values: new object[,]
                {
                    { 1, new DateTime(2025, 4, 14, 10, 39, 2, 728, DateTimeKind.Local).AddTicks(915), null, "TcKimlik", false, "DosyaEvrak", null },
                    { 2, new DateTime(2025, 4, 14, 10, 39, 2, 728, DateTimeKind.Local).AddTicks(919), null, "Sici Kaydı", false, "KullaniciEvrak", null }
                });

            migrationBuilder.InsertData(
                table: "Districts",
                columns: new[] { "ID", "CityID", "Name" },
                values: new object[,]
                {
                    { 1, 1, "ALADAĞ" },
                    { 2, 1, "CEYHAN" },
                    { 3, 1, "ÇUKUROVA" },
                    { 4, 1, "FEKE" },
                    { 5, 1, "İMAMOĞLU" },
                    { 6, 1, "KARAİSALI" },
                    { 7, 1, "KARATAŞ" },
                    { 8, 1, "KOZAN" },
                    { 9, 1, "POZANTI" },
                    { 10, 1, "SAİMBEYLİ" },
                    { 11, 1, "SARIÇAM" },
                    { 12, 1, "SEYHAN" },
                    { 13, 1, "TUFANBEYLİ" },
                    { 14, 1, "YUMURTALIK" },
                    { 15, 1, "YÜREĞİR" },
                    { 16, 2, "BESNİ" },
                    { 17, 2, "ÇELİKHAN" },
                    { 18, 2, "GERGER" },
                    { 19, 2, "GÖLBAŞI" },
                    { 20, 2, "KAHTA" },
                    { 21, 2, "MERKEZ" },
                    { 22, 2, "SAMSAT" },
                    { 23, 2, "SİNCİK" },
                    { 24, 2, "TUT" },
                    { 25, 3, "BAŞMAKÇI" },
                    { 26, 3, "BAYAT" },
                    { 27, 3, "BOLVADİN" },
                    { 28, 3, "ÇAY" },
                    { 29, 3, "ÇOBANLAR" },
                    { 30, 3, "DAZKIRI" },
                    { 31, 3, "DİNAR" },
                    { 32, 3, "EMİRDAĞ" },
                    { 33, 3, "EVCİLER" },
                    { 34, 3, "HOCALAR" },
                    { 35, 3, "İHSANİYE" },
                    { 36, 3, "İSCEHİSAR" },
                    { 37, 3, "KIZILÖREN" },
                    { 38, 3, "MERKEZ" },
                    { 39, 3, "SANDIKLI" },
                    { 40, 3, "SİNANPAŞA" },
                    { 41, 3, "SULTANDAĞI" },
                    { 42, 3, "ŞUHUT" },
                    { 43, 4, "DİYADİN" },
                    { 44, 4, "DOĞUBAYAZIT" },
                    { 45, 4, "ELEŞKİRT" },
                    { 46, 4, "HAMUR" },
                    { 47, 4, "MERKEZ" },
                    { 48, 4, "PATNOS" },
                    { 49, 4, "TAŞLIÇAY" },
                    { 50, 4, "TUTAK" },
                    { 51, 5, "GÖYNÜCEK" },
                    { 52, 5, "GÜMÜŞHACIKÖY" },
                    { 53, 5, "HAMAMÖZÜ" },
                    { 54, 5, "MERKEZ" },
                    { 55, 5, "MERZİFON" },
                    { 56, 5, "SULUOVA" },
                    { 57, 5, "TAŞOVA" },
                    { 58, 6, "AKYURT" },
                    { 59, 6, "ALTINDAĞ" },
                    { 60, 6, "AYAŞ" },
                    { 61, 6, "BALA" },
                    { 62, 6, "BEYPAZARI" },
                    { 63, 6, "ÇAMLIDERE" },
                    { 64, 6, "ÇANKAYA" },
                    { 65, 6, "ÇUBUK" },
                    { 66, 6, "ELMADAĞ" },
                    { 67, 6, "ETİMESGUT" },
                    { 68, 6, "EVREN" },
                    { 69, 6, "GÖLBAŞI" },
                    { 70, 6, "GÜDÜL" },
                    { 71, 6, "HAYMANA" },
                    { 72, 6, "KAHRAMANKAZAN" },
                    { 73, 6, "KALECİK" },
                    { 74, 6, "KEÇİÖREN" },
                    { 75, 6, "KIZILCAHAMAM" },
                    { 76, 6, "MAMAK" },
                    { 77, 6, "NALLIHAN" },
                    { 78, 6, "POLATLI" },
                    { 79, 6, "PURSAKLAR" },
                    { 80, 6, "SİNCAN" },
                    { 81, 6, "ŞEREFLİKOÇHİSAR" },
                    { 82, 6, "YENİMAHALLE" },
                    { 83, 7, "AKSEKİ" },
                    { 84, 7, "AKSU" },
                    { 85, 7, "ALANYA" },
                    { 86, 7, "DEMRE" },
                    { 87, 7, "DÖŞEMEALTI" },
                    { 88, 7, "ELMALI" },
                    { 89, 7, "FİNİKE" },
                    { 90, 7, "GAZİPAŞA" },
                    { 91, 7, "GÜNDOĞMUŞ" },
                    { 92, 7, "İBRADI" },
                    { 93, 7, "KAŞ" },
                    { 94, 7, "KEMER" },
                    { 95, 7, "KEPEZ" },
                    { 96, 7, "KONYAALTI" },
                    { 97, 7, "KORKUTELİ" },
                    { 98, 7, "KUMLUCA" },
                    { 99, 7, "MANAVGAT" },
                    { 100, 7, "MURATPAŞA" },
                    { 101, 7, "SERİK" },
                    { 102, 8, "ARDANUÇ" },
                    { 103, 8, "ARHAVİ" },
                    { 104, 8, "BORÇKA" },
                    { 105, 8, "HOPA" },
                    { 106, 8, "KEMALPAŞA" },
                    { 107, 8, "MERKEZ" },
                    { 108, 8, "MURGUL" },
                    { 109, 8, "ŞAVŞAT" },
                    { 110, 8, "YUSUFELİ" },
                    { 111, 9, "BOZDOĞAN" },
                    { 112, 9, "BUHARKENT" },
                    { 113, 9, "ÇİNE" },
                    { 114, 9, "DİDİM" },
                    { 115, 9, "EFELER" },
                    { 116, 9, "GERMENCİK" },
                    { 117, 9, "İNCİRLİOVA" },
                    { 118, 9, "KARACASU" },
                    { 119, 9, "KARPUZLU" },
                    { 120, 9, "KOÇARLI" },
                    { 121, 9, "KÖŞK" },
                    { 122, 9, "KUŞADASI" },
                    { 123, 9, "KUYUCAK" },
                    { 124, 9, "NAZİLLİ" },
                    { 125, 9, "SÖKE" },
                    { 126, 9, "SULTANHİSAR" },
                    { 127, 9, "YENİPAZAR" },
                    { 128, 10, "ALTIEYLÜL" },
                    { 129, 10, "AYVALIK" },
                    { 130, 10, "BALYA" },
                    { 131, 10, "BANDIRMA" },
                    { 132, 10, "BİGADİÇ" },
                    { 133, 10, "BURHANİYE" },
                    { 134, 10, "DURSUNBEY" },
                    { 135, 10, "EDREMİT" },
                    { 136, 10, "ERDEK" },
                    { 137, 10, "GÖMEÇ" },
                    { 138, 10, "GÖNEN" },
                    { 139, 10, "HAVRAN" },
                    { 140, 10, "İVRİNDİ" },
                    { 141, 10, "KARESİ" },
                    { 142, 10, "KEPSUT" },
                    { 143, 10, "MANYAS" },
                    { 144, 10, "MARMARA" },
                    { 145, 10, "SAVAŞTEPE" },
                    { 146, 10, "SINDIRGI" },
                    { 147, 10, "SUSURLUK" },
                    { 148, 11, "BOZÜYÜK" },
                    { 149, 11, "GÖLPAZARI" },
                    { 150, 11, "İNHİSAR" },
                    { 151, 11, "MERKEZ" },
                    { 152, 11, "OSMANELİ" },
                    { 153, 11, "PAZARYERİ" },
                    { 154, 11, "SÖĞÜT" },
                    { 155, 11, "YENİPAZAR" },
                    { 156, 12, "ADAKLI" },
                    { 157, 12, "GENÇ" },
                    { 158, 12, "KARLIOVA" },
                    { 159, 12, "KİĞI" },
                    { 160, 12, "MERKEZ" },
                    { 161, 12, "SOLHAN" },
                    { 162, 12, "YAYLADERE" },
                    { 163, 12, "YEDİSU" },
                    { 164, 13, "ADİLCEVAZ" },
                    { 165, 13, "AHLAT" },
                    { 166, 13, "GÜROYMAK" },
                    { 167, 13, "HİZAN" },
                    { 168, 13, "MERKEZ" },
                    { 169, 13, "MUTKİ" },
                    { 170, 13, "TATVAN" },
                    { 171, 14, "DÖRTDİVAN" },
                    { 172, 14, "GEREDE" },
                    { 173, 14, "GÖYNÜK" },
                    { 174, 14, "KIBRISCIK" },
                    { 175, 14, "MENGEN" },
                    { 176, 14, "MERKEZ" },
                    { 177, 14, "MUDURNU" },
                    { 178, 14, "SEBEN" },
                    { 179, 14, "YENİÇAĞA" },
                    { 180, 15, "AĞLASUN" },
                    { 181, 15, "ALTINYAYLA" },
                    { 182, 15, "BUCAK" },
                    { 183, 15, "ÇAVDIR" },
                    { 184, 15, "ÇELTİKÇİ" },
                    { 185, 15, "GÖLHİSAR" },
                    { 186, 15, "KARAMANLI" },
                    { 187, 15, "KEMER" },
                    { 188, 15, "MERKEZ" },
                    { 189, 15, "TEFENNİ" },
                    { 190, 15, "YEŞİLOVA" },
                    { 191, 16, "BÜYÜKORHAN" },
                    { 192, 16, "GEMLİK" },
                    { 193, 16, "GÜRSU" },
                    { 194, 16, "HARMANCIK" },
                    { 195, 16, "İNEGÖL" },
                    { 196, 16, "İZNİK" },
                    { 197, 16, "KARACABEY" },
                    { 198, 16, "KELES" },
                    { 199, 16, "KESTEL" },
                    { 200, 16, "MUDANYA" },
                    { 201, 16, "MUSTAFAKEMALPAŞA" },
                    { 202, 16, "NİLÜFER" },
                    { 203, 16, "ORHANELİ" },
                    { 204, 16, "ORHANGAZİ" },
                    { 205, 16, "OSMANGAZİ" },
                    { 206, 16, "YENİŞEHİR" },
                    { 207, 16, "YILDIRIM" },
                    { 208, 17, "AYVACIK" },
                    { 209, 17, "BAYRAMİÇ" },
                    { 210, 17, "BİGA" },
                    { 211, 17, "BOZCAADA" },
                    { 212, 17, "ÇAN" },
                    { 213, 17, "ECEABAT" },
                    { 214, 17, "EZİNE" },
                    { 215, 17, "GELİBOLU" },
                    { 216, 17, "GÖKÇEADA" },
                    { 217, 17, "LAPSEKİ" },
                    { 218, 17, "MERKEZ" },
                    { 219, 17, "YENİCE" },
                    { 220, 18, "ATKARACALAR" },
                    { 221, 18, "BAYRAMÖREN" },
                    { 222, 18, "ÇERKEŞ" },
                    { 223, 18, "ELDİVAN" },
                    { 224, 18, "ILGAZ" },
                    { 225, 18, "KIZILIRMAK" },
                    { 226, 18, "KORGUN" },
                    { 227, 18, "KURŞUNLU" },
                    { 228, 18, "MERKEZ" },
                    { 229, 18, "ORTA" },
                    { 230, 18, "ŞABANÖZÜ" },
                    { 231, 18, "YAPRAKLI" },
                    { 232, 19, "ALACA" },
                    { 233, 19, "BAYAT" },
                    { 234, 19, "BOĞAZKALE" },
                    { 235, 19, "DODURGA" },
                    { 236, 19, "İSKİLİP" },
                    { 237, 19, "KARGI" },
                    { 238, 19, "LAÇİN" },
                    { 239, 19, "MECİTÖZÜ" },
                    { 240, 19, "MERKEZ" },
                    { 241, 19, "OĞUZLAR" },
                    { 242, 19, "ORTAKÖY" },
                    { 243, 19, "OSMANCIK" },
                    { 244, 19, "SUNGURLU" },
                    { 245, 19, "UĞURLUDAĞ" },
                    { 246, 20, "ACIPAYAM" },
                    { 247, 20, "BABADAĞ" },
                    { 248, 20, "BAKLAN" },
                    { 249, 20, "BEKİLLİ" },
                    { 250, 20, "BEYAĞAÇ" },
                    { 251, 20, "BOZKURT" },
                    { 252, 20, "BULDAN" },
                    { 253, 20, "ÇAL" },
                    { 254, 20, "ÇAMELİ" },
                    { 255, 20, "ÇARDAK" },
                    { 256, 20, "ÇİVRİL" },
                    { 257, 20, "GÜNEY" },
                    { 258, 20, "HONAZ" },
                    { 259, 20, "KALE" },
                    { 260, 20, "MERKEZEFENDİ" },
                    { 261, 20, "PAMUKKALE" },
                    { 262, 20, "SARAYKÖY" },
                    { 263, 20, "SERİNHİSAR" },
                    { 264, 20, "TAVAS" },
                    { 265, 21, "BAĞLAR" },
                    { 266, 21, "BİSMİL" },
                    { 267, 21, "ÇERMİK" },
                    { 268, 21, "ÇINAR" },
                    { 269, 21, "ÇÜNGÜŞ" },
                    { 270, 21, "DİCLE" },
                    { 271, 21, "EĞİL" },
                    { 272, 21, "ERGANİ" },
                    { 273, 21, "HANİ" },
                    { 274, 21, "HAZRO" },
                    { 275, 21, "KAYAPINAR" },
                    { 276, 21, "KOCAKÖY" },
                    { 277, 21, "KULP" },
                    { 278, 21, "LİCE" },
                    { 279, 21, "SİLVAN" },
                    { 280, 21, "SUR" },
                    { 281, 21, "YENİŞEHİR" },
                    { 282, 22, "ENEZ" },
                    { 283, 22, "HAVSA" },
                    { 284, 22, "İPSALA" },
                    { 285, 22, "KEŞAN" },
                    { 286, 22, "LALAPAŞA" },
                    { 287, 22, "MERİÇ" },
                    { 288, 22, "MERKEZ" },
                    { 289, 22, "SÜLOĞLU" },
                    { 290, 22, "UZUNKÖPRÜ" },
                    { 291, 23, "AĞIN" },
                    { 292, 23, "ALACAKAYA" },
                    { 293, 23, "ARICAK" },
                    { 294, 23, "BASKİL" },
                    { 295, 23, "KARAKOÇAN" },
                    { 296, 23, "KEBAN" },
                    { 297, 23, "KOVANCILAR" },
                    { 298, 23, "MADEN" },
                    { 299, 23, "MERKEZ" },
                    { 300, 23, "PALU" },
                    { 301, 23, "SİVRİCE" },
                    { 302, 24, "ÇAYIRLI" },
                    { 303, 24, "İLİÇ" },
                    { 304, 24, "KEMAH" },
                    { 305, 24, "KEMALİYE" },
                    { 306, 24, "MERKEZ" },
                    { 307, 24, "OTLUKBELİ" },
                    { 308, 24, "REFAHİYE" },
                    { 309, 24, "TERCAN" },
                    { 310, 24, "ÜZÜMLÜ" },
                    { 311, 25, "AŞKALE" },
                    { 312, 25, "AZİZİYE" },
                    { 313, 25, "ÇAT" },
                    { 314, 25, "HINIS" },
                    { 315, 25, "HORASAN" },
                    { 316, 25, "İSPİR" },
                    { 317, 25, "KARAÇOBAN" },
                    { 318, 25, "KARAYAZI" },
                    { 319, 25, "KÖPRÜKÖY" },
                    { 320, 25, "NARMAN" },
                    { 321, 25, "OLTU" },
                    { 322, 25, "OLUR" },
                    { 323, 25, "PALANDÖKEN" },
                    { 324, 25, "PASİNLER" },
                    { 325, 25, "PAZARYOLU" },
                    { 326, 25, "ŞENKAYA" },
                    { 327, 25, "TEKMAN" },
                    { 328, 25, "TORTUM" },
                    { 329, 25, "UZUNDERE" },
                    { 330, 25, "YAKUTİYE" },
                    { 331, 26, "ALPU" },
                    { 332, 26, "BEYLİKOVA" },
                    { 333, 26, "ÇİFTELER" },
                    { 334, 26, "GÜNYÜZÜ" },
                    { 335, 26, "HAN" },
                    { 336, 26, "İNÖNÜ" },
                    { 337, 26, "MAHMUDİYE" },
                    { 338, 26, "MİHALGAZİ" },
                    { 339, 26, "MİHALIÇÇIK" },
                    { 340, 26, "ODUNPAZARI" },
                    { 341, 26, "SARICAKAYA" },
                    { 342, 26, "SEYİTGAZİ" },
                    { 343, 26, "SİVRİHİSAR" },
                    { 344, 26, "TEPEBAŞI" },
                    { 345, 27, "ARABAN" },
                    { 346, 27, "İSLAHİYE" },
                    { 347, 27, "KARKAMIŞ" },
                    { 348, 27, "NİZİP" },
                    { 349, 27, "NURDAĞI" },
                    { 350, 27, "OĞUZELİ" },
                    { 351, 27, "ŞAHİNBEY" },
                    { 352, 27, "ŞEHİTKAMİL" },
                    { 353, 27, "YAVUZELİ" },
                    { 354, 28, "ALUCRA" },
                    { 355, 28, "BULANCAK" },
                    { 356, 28, "ÇAMOLUK" },
                    { 357, 28, "ÇANAKÇI" },
                    { 358, 28, "DERELİ" },
                    { 359, 28, "DOĞANKENT" },
                    { 360, 28, "ESPİYE" },
                    { 361, 28, "EYNESİL" },
                    { 362, 28, "GÖRELE" },
                    { 363, 28, "GÜCE" },
                    { 364, 28, "KEŞAP" },
                    { 365, 28, "MERKEZ" },
                    { 366, 28, "PİRAZİZ" },
                    { 367, 28, "ŞEBİNKARAHİSAR" },
                    { 368, 28, "TİREBOLU" },
                    { 369, 28, "YAĞLIDERE" },
                    { 370, 29, "KELKİT" },
                    { 371, 29, "KÖSE" },
                    { 372, 29, "KÜRTÜN" },
                    { 373, 29, "MERKEZ" },
                    { 374, 29, "ŞİRAN" },
                    { 375, 29, "TORUL" },
                    { 376, 30, "ÇUKURCA" },
                    { 377, 30, "DERECİK" },
                    { 378, 30, "MERKEZ" },
                    { 379, 30, "ŞEMDİNLİ" },
                    { 380, 30, "YÜKSEKOVA" },
                    { 381, 31, "ALTINÖZÜ" },
                    { 382, 31, "ANTAKYA" },
                    { 383, 31, "ARSUZ" },
                    { 384, 31, "BELEN" },
                    { 385, 31, "DEFNE" },
                    { 386, 31, "DÖRTYOL" },
                    { 387, 31, "ERZİN" },
                    { 388, 31, "HASSA" },
                    { 389, 31, "İSKENDERUN" },
                    { 390, 31, "KIRIKHAN" },
                    { 391, 31, "KUMLU" },
                    { 392, 31, "PAYAS" },
                    { 393, 31, "REYHANLI" },
                    { 394, 31, "SAMANDAĞ" },
                    { 395, 31, "YAYLADAĞI" },
                    { 396, 32, "AKSU" },
                    { 397, 32, "ATABEY" },
                    { 398, 32, "EĞİRDİR" },
                    { 399, 32, "GELENDOST" },
                    { 400, 32, "GÖNEN" },
                    { 401, 32, "KEÇİBORLU" },
                    { 402, 32, "MERKEZ" },
                    { 403, 32, "SENİRKENT" },
                    { 404, 32, "SÜTÇÜLER" },
                    { 405, 32, "ŞARKİKARAAĞAÇ" },
                    { 406, 32, "ULUBORLU" },
                    { 407, 32, "YALVAÇ" },
                    { 408, 32, "YENİŞARBADEMLİ" },
                    { 409, 33, "AKDENİZ" },
                    { 410, 33, "ANAMUR" },
                    { 411, 33, "AYDINCIK" },
                    { 412, 33, "BOZYAZI" },
                    { 413, 33, "ÇAMLIYAYLA" },
                    { 414, 33, "ERDEMLİ" },
                    { 415, 33, "GÜLNAR" },
                    { 416, 33, "MEZİTLİ" },
                    { 417, 33, "MUT" },
                    { 418, 33, "SİLİFKE" },
                    { 419, 33, "TARSUS" },
                    { 420, 33, "TOROSLAR" },
                    { 421, 33, "YENİŞEHİR" },
                    { 422, 34, "ADALAR" },
                    { 423, 34, "ARNAVUTKÖY" },
                    { 424, 34, "ATAŞEHİR" },
                    { 425, 34, "AVCILAR" },
                    { 426, 34, "BAĞCILAR" },
                    { 427, 34, "BAHÇELİEVLER" },
                    { 428, 34, "BAKIRKÖY" },
                    { 429, 34, "BAŞAKŞEHİR" },
                    { 430, 34, "BAYRAMPAŞA" },
                    { 431, 34, "BEŞİKTAŞ" },
                    { 432, 34, "BEYKOZ" },
                    { 433, 34, "BEYLİKDÜZÜ" },
                    { 434, 34, "BEYOĞLU" },
                    { 435, 34, "BÜYÜKÇEKMECE" },
                    { 436, 34, "ÇATALCA" },
                    { 437, 34, "ÇEKMEKÖY" },
                    { 438, 34, "ESENLER" },
                    { 439, 34, "ESENYURT" },
                    { 440, 34, "EYÜPSULTAN" },
                    { 441, 34, "FATİH" },
                    { 442, 34, "GAZİOSMANPAŞA" },
                    { 443, 34, "GÜNGÖREN" },
                    { 444, 34, "KADIKÖY" },
                    { 445, 34, "KAĞITHANE" },
                    { 446, 34, "KARTAL" },
                    { 447, 34, "KÜÇÜKÇEKMECE" },
                    { 448, 34, "MALTEPE" },
                    { 449, 34, "PENDİK" },
                    { 450, 34, "SANCAKTEPE" },
                    { 451, 34, "SARIYER" },
                    { 452, 34, "SİLİVRİ" },
                    { 453, 34, "SULTANBEYLİ" },
                    { 454, 34, "SULTANGAZİ" },
                    { 455, 34, "ŞİLE" },
                    { 456, 34, "ŞİŞLİ" },
                    { 457, 34, "TUZLA" },
                    { 458, 34, "ÜMRANİYE" },
                    { 459, 34, "ÜSKÜDAR" },
                    { 460, 34, "ZEYTİNBURNU" },
                    { 461, 35, "ALİAĞA" },
                    { 462, 35, "BALÇOVA" },
                    { 463, 35, "BAYINDIR" },
                    { 464, 35, "BAYRAKLI" },
                    { 465, 35, "BERGAMA" },
                    { 466, 35, "BEYDAĞ" },
                    { 467, 35, "BORNOVA" },
                    { 468, 35, "BUCA" },
                    { 469, 35, "ÇEŞME" },
                    { 470, 35, "ÇİĞLİ" },
                    { 471, 35, "DİKİLİ" },
                    { 472, 35, "FOÇA" },
                    { 473, 35, "GAZİEMİR" },
                    { 474, 35, "GÜZELBAHÇE" },
                    { 475, 35, "KARABAĞLAR" },
                    { 476, 35, "KARABURUN" },
                    { 477, 35, "KARŞIYAKA" },
                    { 478, 35, "KEMALPAŞA" },
                    { 479, 35, "KINIK" },
                    { 480, 35, "KİRAZ" },
                    { 481, 35, "KONAK" },
                    { 482, 35, "MENDERES" },
                    { 483, 35, "MENEMEN" },
                    { 484, 35, "NARLIDERE" },
                    { 485, 35, "ÖDEMİŞ" },
                    { 486, 35, "SEFERİHİSAR" },
                    { 487, 35, "SELÇUK" },
                    { 488, 35, "TİRE" },
                    { 489, 35, "TORBALI" },
                    { 490, 35, "URLA" },
                    { 491, 36, "AKYAKA" },
                    { 492, 36, "ARPAÇAY" },
                    { 493, 36, "DİGOR" },
                    { 494, 36, "KAĞIZMAN" },
                    { 495, 36, "MERKEZ" },
                    { 496, 36, "SARIKAMIŞ" },
                    { 497, 36, "SELİM" },
                    { 498, 36, "SUSUZ" },
                    { 499, 37, "ABANA" },
                    { 500, 37, "AĞLI" },
                    { 501, 37, "ARAÇ" },
                    { 502, 37, "AZDAVAY" },
                    { 503, 37, "BOZKURT" },
                    { 504, 37, "CİDE" },
                    { 505, 37, "ÇATALZEYTİN" },
                    { 506, 37, "DADAY" },
                    { 507, 37, "DEVREKANİ" },
                    { 508, 37, "DOĞANYURT" },
                    { 509, 37, "HANÖNÜ" },
                    { 510, 37, "İHSANGAZİ" },
                    { 511, 37, "İNEBOLU" },
                    { 512, 37, "KÜRE" },
                    { 513, 37, "MERKEZ" },
                    { 514, 37, "PINARBAŞI" },
                    { 515, 37, "SEYDİLER" },
                    { 516, 37, "ŞENPAZAR" },
                    { 517, 37, "TAŞKÖPRÜ" },
                    { 518, 37, "TOSYA" },
                    { 519, 38, "AKKIŞLA" },
                    { 520, 38, "BÜNYAN" },
                    { 521, 38, "DEVELİ" },
                    { 522, 38, "FELAHİYE" },
                    { 523, 38, "HACILAR" },
                    { 524, 38, "İNCESU" },
                    { 525, 38, "KOCASİNAN" },
                    { 526, 38, "MELİKGAZİ" },
                    { 527, 38, "ÖZVATAN" },
                    { 528, 38, "PINARBAŞI" },
                    { 529, 38, "SARIOĞLAN" },
                    { 530, 38, "SARIZ" },
                    { 531, 38, "TALAS" },
                    { 532, 38, "TOMARZA" },
                    { 533, 38, "YAHYALI" },
                    { 534, 38, "YEŞİLHİSAR" },
                    { 535, 39, "BABAESKİ" },
                    { 536, 39, "DEMİRKÖY" },
                    { 537, 39, "KOFÇAZ" },
                    { 538, 39, "LÜLEBURGAZ" },
                    { 539, 39, "MERKEZ" },
                    { 540, 39, "PEHLİVANKÖY" },
                    { 541, 39, "PINARHİSAR" },
                    { 542, 39, "VİZE" },
                    { 543, 40, "AKÇAKENT" },
                    { 544, 40, "AKPINAR" },
                    { 545, 40, "BOZTEPE" },
                    { 546, 40, "ÇİÇEKDAĞI" },
                    { 547, 40, "KAMAN" },
                    { 548, 40, "MERKEZ" },
                    { 549, 40, "MUCUR" },
                    { 550, 41, "BAŞİSKELE" },
                    { 551, 41, "ÇAYIROVA" },
                    { 552, 41, "DARICA" },
                    { 553, 41, "DERİNCE" },
                    { 554, 41, "DİLOVASI" },
                    { 555, 41, "GEBZE" },
                    { 556, 41, "GÖLCÜK" },
                    { 557, 41, "İZMİT" },
                    { 558, 41, "KANDIRA" },
                    { 559, 41, "KARAMÜRSEL" },
                    { 560, 41, "KARTEPE" },
                    { 561, 41, "KÖRFEZ" },
                    { 562, 42, "AHIRLI" },
                    { 563, 42, "AKÖREN" },
                    { 564, 42, "AKŞEHİR" },
                    { 565, 42, "ALTINEKİN" },
                    { 566, 42, "BEYŞEHİR" },
                    { 567, 42, "BOZKIR" },
                    { 568, 42, "CİHANBEYLİ" },
                    { 569, 42, "ÇELTİK" },
                    { 570, 42, "ÇUMRA" },
                    { 571, 42, "DERBENT" },
                    { 572, 42, "DEREBUCAK" },
                    { 573, 42, "DOĞANHİSAR" },
                    { 574, 42, "EMİRGAZİ" },
                    { 575, 42, "EREĞLİ" },
                    { 576, 42, "GÜNEYSINIR" },
                    { 577, 42, "HADİM" },
                    { 578, 42, "HALKAPINAR" },
                    { 579, 42, "HÜYÜK" },
                    { 580, 42, "ILGIN" },
                    { 581, 42, "KADINHANI" },
                    { 582, 42, "KARAPINAR" },
                    { 583, 42, "KARATAY" },
                    { 584, 42, "KULU" },
                    { 585, 42, "MERAM" },
                    { 586, 42, "SARAYÖNÜ" },
                    { 587, 42, "SELÇUKLU" },
                    { 588, 42, "SEYDİŞEHİR" },
                    { 589, 42, "TAŞKENT" },
                    { 590, 42, "TUZLUKÇU" },
                    { 591, 42, "YALIHÜYÜK" },
                    { 592, 42, "YUNAK" },
                    { 593, 43, "ALTINTAŞ" },
                    { 594, 43, "ASLANAPA" },
                    { 595, 43, "ÇAVDARHİSAR" },
                    { 596, 43, "DOMANİÇ" },
                    { 597, 43, "DUMLUPINAR" },
                    { 598, 43, "EMET" },
                    { 599, 43, "GEDİZ" },
                    { 600, 43, "HİSARCIK" },
                    { 601, 43, "MERKEZ" },
                    { 602, 43, "PAZARLAR" },
                    { 603, 43, "SİMAV" },
                    { 604, 43, "ŞAPHANE" },
                    { 605, 43, "TAVŞANLI" },
                    { 606, 44, "AKÇADAĞ" },
                    { 607, 44, "ARAPGİR" },
                    { 608, 44, "ARGUVAN" },
                    { 609, 44, "BATTALGAZİ" },
                    { 610, 44, "DARENDE" },
                    { 611, 44, "DOĞANŞEHİR" },
                    { 612, 44, "DOĞANYOL" },
                    { 613, 44, "HEKİMHAN" },
                    { 614, 44, "KALE" },
                    { 615, 44, "KULUNCAK" },
                    { 616, 44, "PÜTÜRGE" },
                    { 617, 44, "YAZIHAN" },
                    { 618, 44, "YEŞİLYURT" },
                    { 619, 45, "AHMETLİ" },
                    { 620, 45, "AKHİSAR" },
                    { 621, 45, "ALAŞEHİR" },
                    { 622, 45, "DEMİRCİ" },
                    { 623, 45, "GÖLMARMARA" },
                    { 624, 45, "GÖRDES" },
                    { 625, 45, "KIRKAĞAÇ" },
                    { 626, 45, "KÖPRÜBAŞI" },
                    { 627, 45, "KULA" },
                    { 628, 45, "SALİHLİ" },
                    { 629, 45, "SARIGÖL" },
                    { 630, 45, "SARUHANLI" },
                    { 631, 45, "SELENDİ" },
                    { 632, 45, "SOMA" },
                    { 633, 45, "ŞEHZADELER" },
                    { 634, 45, "TURGUTLU" },
                    { 635, 45, "YUNUSEMRE" },
                    { 636, 46, "AFŞİN" },
                    { 637, 46, "ANDIRIN" },
                    { 638, 46, "ÇAĞLAYANCERİT" },
                    { 639, 46, "DULKADİROĞLU" },
                    { 640, 46, "EKİNÖZÜ" },
                    { 641, 46, "ELBİSTAN" },
                    { 642, 46, "GÖKSUN" },
                    { 643, 46, "NURHAK" },
                    { 644, 46, "ONİKİŞUBAT" },
                    { 645, 46, "PAZARCIK" },
                    { 646, 46, "TÜRKOĞLU" },
                    { 647, 47, "ARTUKLU" },
                    { 648, 47, "DARGEÇİT" },
                    { 649, 47, "DERİK" },
                    { 650, 47, "KIZILTEPE" },
                    { 651, 47, "MAZIDAĞI" },
                    { 652, 47, "MİDYAT" },
                    { 653, 47, "NUSAYBİN" },
                    { 654, 47, "ÖMERLİ" },
                    { 655, 47, "SAVUR" },
                    { 656, 47, "YEŞİLLİ" },
                    { 657, 48, "BODRUM" },
                    { 658, 48, "DALAMAN" },
                    { 659, 48, "DATÇA" },
                    { 660, 48, "FETHİYE" },
                    { 661, 48, "KAVAKLIDERE" },
                    { 662, 48, "KÖYCEĞİZ" },
                    { 663, 48, "MARMARİS" },
                    { 664, 48, "MENTEŞE" },
                    { 665, 48, "MİLAS" },
                    { 666, 48, "ORTACA" },
                    { 667, 48, "SEYDİKEMER" },
                    { 668, 48, "ULA" },
                    { 669, 48, "YATAĞAN" },
                    { 670, 49, "BULANIK" },
                    { 671, 49, "HASKÖY" },
                    { 672, 49, "KORKUT" },
                    { 673, 49, "MALAZGİRT" },
                    { 674, 49, "MERKEZ" },
                    { 675, 49, "VARTO" },
                    { 676, 50, "ACIGÖL" },
                    { 677, 50, "AVANOS" },
                    { 678, 50, "DERİNKUYU" },
                    { 679, 50, "GÜLŞEHİR" },
                    { 680, 50, "HACIBEKTAŞ" },
                    { 681, 50, "KOZAKLI" },
                    { 682, 50, "MERKEZ" },
                    { 683, 50, "ÜRGÜP" },
                    { 684, 51, "ALTUNHİSAR" },
                    { 685, 51, "BOR" },
                    { 686, 51, "ÇAMARDI" },
                    { 687, 51, "ÇİFTLİK" },
                    { 688, 51, "MERKEZ" },
                    { 689, 51, "ULUKIŞLA" },
                    { 690, 52, "AKKUŞ" },
                    { 691, 52, "ALTINORDU" },
                    { 692, 52, "AYBASTI" },
                    { 693, 52, "ÇAMAŞ" },
                    { 694, 52, "ÇATALPINAR" },
                    { 695, 52, "ÇAYBAŞI" },
                    { 696, 52, "FATSA" },
                    { 697, 52, "GÖLKÖY" },
                    { 698, 52, "GÜLYALI" },
                    { 699, 52, "GÜRGENTEPE" },
                    { 700, 52, "İKİZCE" },
                    { 701, 52, "KABADÜZ" },
                    { 702, 52, "KABATAŞ" },
                    { 703, 52, "KORGAN" },
                    { 704, 52, "KUMRU" },
                    { 705, 52, "MESUDİYE" },
                    { 706, 52, "PERŞEMBE" },
                    { 707, 52, "ULUBEY" },
                    { 708, 52, "ÜNYE" },
                    { 709, 53, "ARDEŞEN" },
                    { 710, 53, "ÇAMLIHEMŞİN" },
                    { 711, 53, "ÇAYELİ" },
                    { 712, 53, "DEREPAZARI" },
                    { 713, 53, "FINDIKLI" },
                    { 714, 53, "GÜNEYSU" },
                    { 715, 53, "HEMŞİN" },
                    { 716, 53, "İKİZDERE" },
                    { 717, 53, "İYİDERE" },
                    { 718, 53, "KALKANDERE" },
                    { 719, 53, "MERKEZ" },
                    { 720, 53, "PAZAR" },
                    { 721, 54, "ADAPAZARI" },
                    { 722, 54, "AKYAZI" },
                    { 723, 54, "ARİFİYE" },
                    { 724, 54, "ERENLER" },
                    { 725, 54, "FERİZLİ" },
                    { 726, 54, "GEYVE" },
                    { 727, 54, "HENDEK" },
                    { 728, 54, "KARAPÜRÇEK" },
                    { 729, 54, "KARASU" },
                    { 730, 54, "KAYNARCA" },
                    { 731, 54, "KOCAALİ" },
                    { 732, 54, "PAMUKOVA" },
                    { 733, 54, "SAPANCA" },
                    { 734, 54, "SERDİVAN" },
                    { 735, 54, "SÖĞÜTLÜ" },
                    { 736, 54, "TARAKLI" },
                    { 737, 55, "ALAÇAM" },
                    { 738, 55, "ASARCIK" },
                    { 739, 55, "ATAKUM" },
                    { 740, 55, "AYVACIK" },
                    { 741, 55, "BAFRA" },
                    { 742, 55, "CANİK" },
                    { 743, 55, "ÇARŞAMBA" },
                    { 744, 55, "HAVZA" },
                    { 745, 55, "İLKADIM" },
                    { 746, 55, "KAVAK" },
                    { 747, 55, "LADİK" },
                    { 748, 55, "SALIPAZARI" },
                    { 749, 55, "TEKKEKÖY" },
                    { 750, 55, "TERME" },
                    { 751, 55, "VEZİRKÖPRÜ" },
                    { 752, 55, "YAKAKENT" },
                    { 753, 55, "19 MAYIS" },
                    { 754, 56, "BAYKAN" },
                    { 755, 56, "ERUH" },
                    { 756, 56, "KURTALAN" },
                    { 757, 56, "MERKEZ" },
                    { 758, 56, "PERVARİ" },
                    { 759, 56, "ŞİRVAN" },
                    { 760, 56, "TİLLO" },
                    { 761, 57, "AYANCIK" },
                    { 762, 57, "BOYABAT" },
                    { 763, 57, "DİKMEN" },
                    { 764, 57, "DURAĞAN" },
                    { 765, 57, "ERFELEK" },
                    { 766, 57, "GERZE" },
                    { 767, 57, "MERKEZ" },
                    { 768, 57, "SARAYDÜZÜ" },
                    { 769, 57, "TÜRKELİ" },
                    { 770, 58, "AKINCILAR" },
                    { 771, 58, "ALTINYAYLA" },
                    { 772, 58, "DİVRİĞİ" },
                    { 773, 58, "DOĞANŞAR" },
                    { 774, 58, "GEMEREK" },
                    { 775, 58, "GÖLOVA" },
                    { 776, 58, "GÜRÜN" },
                    { 777, 58, "HAFİK" },
                    { 778, 58, "İMRANLI" },
                    { 779, 58, "KANGAL" },
                    { 780, 58, "KOYULHİSAR" },
                    { 781, 58, "MERKEZ" },
                    { 782, 58, "SUŞEHRİ" },
                    { 783, 58, "ŞARKIŞLA" },
                    { 784, 58, "ULAŞ" },
                    { 785, 58, "YILDIZELİ" },
                    { 786, 58, "ZARA" },
                    { 787, 59, "ÇERKEZKÖY" },
                    { 788, 59, "ÇORLU" },
                    { 789, 59, "ERGENE" },
                    { 790, 59, "HAYRABOLU" },
                    { 791, 59, "KAPAKLI" },
                    { 792, 59, "MALKARA" },
                    { 793, 59, "MARMARAEREĞLİSİ" },
                    { 794, 59, "MURATLI" },
                    { 795, 59, "SARAY" },
                    { 796, 59, "SÜLEYMANPAŞA" },
                    { 797, 59, "ŞARKÖY" },
                    { 798, 60, "ALMUS" },
                    { 799, 60, "ARTOVA" },
                    { 800, 60, "BAŞÇİFTLİK" },
                    { 801, 60, "ERBAA" },
                    { 802, 60, "MERKEZ" },
                    { 803, 60, "NİKSAR" },
                    { 804, 60, "PAZAR" },
                    { 805, 60, "REŞADİYE" },
                    { 806, 60, "SULUSARAY" },
                    { 807, 60, "TURHAL" },
                    { 808, 60, "YEŞİLYURT" },
                    { 809, 60, "ZİLE" },
                    { 810, 61, "AKÇAABAT" },
                    { 811, 61, "ARAKLI" },
                    { 812, 61, "ARSİN" },
                    { 813, 61, "BEŞİKDÜZÜ" },
                    { 814, 61, "ÇARŞIBAŞI" },
                    { 815, 61, "ÇAYKARA" },
                    { 816, 61, "DERNEKPAZARI" },
                    { 817, 61, "DÜZKÖY" },
                    { 818, 61, "HAYRAT" },
                    { 819, 61, "KÖPRÜBAŞI" },
                    { 820, 61, "MAÇKA" },
                    { 821, 61, "OF" },
                    { 822, 61, "ORTAHİSAR" },
                    { 823, 61, "SÜRMENE" },
                    { 824, 61, "ŞALPAZARI" },
                    { 825, 61, "TONYA" },
                    { 826, 61, "VAKFIKEBİR" },
                    { 827, 61, "YOMRA" },
                    { 828, 62, "ÇEMİŞGEZEK" },
                    { 829, 62, "HOZAT" },
                    { 830, 62, "MAZGİRT" },
                    { 831, 62, "MERKEZ" },
                    { 832, 62, "NAZIMİYE" },
                    { 833, 62, "OVACIK" },
                    { 834, 62, "PERTEK" },
                    { 835, 62, "PÜLÜMÜR" },
                    { 836, 63, "AKÇAKALE" },
                    { 837, 63, "BİRECİK" },
                    { 838, 63, "BOZOVA" },
                    { 839, 63, "CEYLANPINAR" },
                    { 840, 63, "EYYÜBİYE" },
                    { 841, 63, "HALFETİ" },
                    { 842, 63, "HALİLİYE" },
                    { 843, 63, "HARRAN" },
                    { 844, 63, "HİLVAN" },
                    { 845, 63, "KARAKÖPRÜ" },
                    { 846, 63, "SİVEREK" },
                    { 847, 63, "SURUÇ" },
                    { 848, 63, "VİRANŞEHİR" },
                    { 849, 64, "BANAZ" },
                    { 850, 64, "EŞME" },
                    { 851, 64, "KARAHALLI" },
                    { 852, 64, "MERKEZ" },
                    { 853, 64, "SİVASLI" },
                    { 854, 64, "ULUBEY" },
                    { 855, 65, "BAHÇESARAY" },
                    { 856, 65, "BAŞKALE" },
                    { 857, 65, "ÇALDIRAN" },
                    { 858, 65, "ÇATAK" },
                    { 859, 65, "EDREMİT" },
                    { 860, 65, "ERCİŞ" },
                    { 861, 65, "GEVAŞ" },
                    { 862, 65, "GÜRPINAR" },
                    { 863, 65, "İPEKYOLU" },
                    { 864, 65, "MURADİYE" },
                    { 865, 65, "ÖZALP" },
                    { 866, 65, "SARAY" },
                    { 867, 65, "TUŞBA" },
                    { 868, 66, "AKDAĞMADENİ" },
                    { 869, 66, "AYDINCIK" },
                    { 870, 66, "BOĞAZLIYAN" },
                    { 871, 66, "ÇANDIR" },
                    { 872, 66, "ÇAYIRALAN" },
                    { 873, 66, "ÇEKEREK" },
                    { 874, 66, "KADIŞEHRİ" },
                    { 875, 66, "MERKEZ" },
                    { 876, 66, "SARAYKENT" },
                    { 877, 66, "SARIKAYA" },
                    { 878, 66, "SORGUN" },
                    { 879, 66, "ŞEFAATLİ" },
                    { 880, 66, "YENİFAKILI" },
                    { 881, 66, "YERKÖY" },
                    { 882, 67, "ALAPLI" },
                    { 883, 67, "ÇAYCUMA" },
                    { 884, 67, "DEVREK" },
                    { 885, 67, "EREĞLİ" },
                    { 886, 67, "GÖKÇEBEY" },
                    { 887, 67, "KİLİMLİ" },
                    { 888, 67, "KOZLU" },
                    { 889, 67, "MERKEZ" },
                    { 890, 68, "AĞAÇÖREN" },
                    { 891, 68, "ESKİL" },
                    { 892, 68, "GÜLAĞAÇ" },
                    { 893, 68, "GÜZELYURT" },
                    { 894, 68, "MERKEZ" },
                    { 895, 68, "ORTAKÖY" },
                    { 896, 68, "SARIYAHŞİ" },
                    { 897, 68, "SULTANHANI" },
                    { 898, 69, "AYDINTEPE" },
                    { 899, 69, "DEMİRÖZÜ" },
                    { 900, 69, "MERKEZ" },
                    { 901, 70, "AYRANCI" },
                    { 902, 70, "BAŞYAYLA" },
                    { 903, 70, "ERMENEK" },
                    { 904, 70, "KAZIMKARABEKİR" },
                    { 905, 70, "MERKEZ" },
                    { 906, 70, "SARIVELİLER" },
                    { 907, 71, "BAHŞİLİ" },
                    { 908, 71, "BALIŞEYH" },
                    { 909, 71, "ÇELEBİ" },
                    { 910, 71, "DELİCE" },
                    { 911, 71, "KARAKEÇİLİ" },
                    { 912, 71, "KESKİN" },
                    { 913, 71, "MERKEZ" },
                    { 914, 71, "SULAKYURT" },
                    { 915, 71, "YAHŞİHAN" },
                    { 916, 72, "BEŞİRİ" },
                    { 917, 72, "GERCÜŞ" },
                    { 918, 72, "HASANKEYF" },
                    { 919, 72, "KOZLUK" },
                    { 920, 72, "MERKEZ" },
                    { 921, 72, "SASON" },
                    { 922, 73, "BEYTÜŞŞEBAP" },
                    { 923, 73, "CİZRE" },
                    { 924, 73, "GÜÇLÜKONAK" },
                    { 925, 73, "İDİL" },
                    { 926, 73, "MERKEZ" },
                    { 927, 73, "SİLOPİ" },
                    { 928, 73, "ULUDERE" },
                    { 929, 74, "AMASRA" },
                    { 930, 74, "KURUCAŞİLE" },
                    { 931, 74, "MERKEZ" },
                    { 932, 74, "ULUS" },
                    { 933, 75, "ÇILDIR" },
                    { 934, 75, "DAMAL" },
                    { 935, 75, "GÖLE" },
                    { 936, 75, "HANAK" },
                    { 937, 75, "MERKEZ" },
                    { 938, 75, "POSOF" },
                    { 939, 76, "ARALIK" },
                    { 940, 76, "KARAKOYUNLU" },
                    { 941, 76, "MERKEZ" },
                    { 942, 76, "TUZLUCA" },
                    { 943, 77, "ALTINOVA" },
                    { 944, 77, "ARMUTLU" },
                    { 945, 77, "ÇINARCIK" },
                    { 946, 77, "ÇİFTLİKKÖY" },
                    { 947, 77, "MERKEZ" },
                    { 948, 77, "TERMAL" },
                    { 949, 78, "EFLANİ" },
                    { 950, 78, "ESKİPAZAR" },
                    { 951, 78, "MERKEZ" },
                    { 952, 78, "OVACIK" },
                    { 953, 78, "SAFRANBOLU" },
                    { 954, 78, "YENİCE" },
                    { 955, 79, "ELBEYLİ" },
                    { 956, 79, "MERKEZ" },
                    { 957, 79, "MUSABEYLİ" },
                    { 958, 79, "POLATELİ" },
                    { 959, 80, "BAHÇE" },
                    { 960, 80, "DÜZİÇİ" },
                    { 961, 80, "HASANBEYLİ" },
                    { 962, 80, "KADİRLİ" },
                    { 963, 80, "MERKEZ" },
                    { 964, 80, "SUMBAS" },
                    { 965, 80, "TOPRAKKALE" },
                    { 966, 81, "AKÇAKOCA" },
                    { 967, 81, "CUMAYERİ" },
                    { 968, 81, "ÇİLİMLİ" },
                    { 969, 81, "GÖLYAKA" },
                    { 970, 81, "GÜMÜŞOVA" },
                    { 971, 81, "KAYNAŞLI" },
                    { 972, 81, "MERKEZ" },
                    { 973, 81, "YIĞILCA" }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "ID", "CityID", "CreatedDate", "DeletedDate", "DistrictID", "Mail", "Name", "Password", "Status", "Surname", "UpdatedDate", "UserName" },
                values: new object[] { 1, 1, new DateTime(2025, 4, 14, 10, 39, 2, 728, DateTimeKind.Local).AddTicks(1028), null, 1, "", "Büşra", "12345", false, "Güneş", null, "busra" });

            migrationBuilder.CreateIndex(
                name: "IX_CaseFileDefendant_caseFileID",
                table: "CaseFileDefendant",
                column: "caseFileID");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFileDefendant_defendantID",
                table: "CaseFileDefendant",
                column: "defendantID");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFileDocument_CaseFileID",
                table: "CaseFileDocument",
                column: "CaseFileID");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFileDocument_CaseFileID1",
                table: "CaseFileDocument",
                column: "CaseFileID1");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFileDocument_DocumentTypeID",
                table: "CaseFileDocument",
                column: "DocumentTypeID");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFileDocument_DocumentTypeID1",
                table: "CaseFileDocument",
                column: "DocumentTypeID1");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFiles_ApplicationTypeID",
                table: "CaseFiles",
                column: "ApplicationTypeID");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFiles_CaseTypeID",
                table: "CaseFiles",
                column: "CaseTypeID");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFiles_CaseTypeID1",
                table: "CaseFiles",
                column: "CaseTypeID1");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFiles_CityID",
                table: "CaseFiles",
                column: "CityID");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFiles_DistrictID",
                table: "CaseFiles",
                column: "DistrictID");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFileShares_CaseFileID",
                table: "CaseFileShares",
                column: "CaseFileID");

            migrationBuilder.CreateIndex(
                name: "IX_CaseFileShares_UserID",
                table: "CaseFileShares",
                column: "UserID");

            migrationBuilder.CreateIndex(
                name: "IX_Districts_CityID",
                table: "Districts",
                column: "CityID");

            migrationBuilder.CreateIndex(
                name: "IX_HesapHareketler_CaseFileID",
                table: "HesapHareketler",
                column: "CaseFileID");

            migrationBuilder.CreateIndex(
                name: "IX_HesapHareketler_CreditID",
                table: "HesapHareketler",
                column: "CreditID");

            migrationBuilder.CreateIndex(
                name: "IX_HesapHareketler_DebtorID",
                table: "HesapHareketler",
                column: "DebtorID");

            migrationBuilder.CreateIndex(
                name: "IX_Users_CityID",
                table: "Users",
                column: "CityID");

            migrationBuilder.CreateIndex(
                name: "IX_Users_DistrictID",
                table: "Users",
                column: "DistrictID");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CaseFileDefendant");

            migrationBuilder.DropTable(
                name: "CaseFileDocument");

            migrationBuilder.DropTable(
                name: "CaseFileShares");

            migrationBuilder.DropTable(
                name: "HesapHareketler");

            migrationBuilder.DropTable(
                name: "Defendants");

            migrationBuilder.DropTable(
                name: "DocumentTypes");

            migrationBuilder.DropTable(
                name: "CaseFiles");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "ApplicationTypes");

            migrationBuilder.DropTable(
                name: "CaseTypes");

            migrationBuilder.DropTable(
                name: "Districts");

            migrationBuilder.DropTable(
                name: "Cities");
        }
    }
}
